### ISSUE TITLE
[VASL] NullPointerException: Cannot invoke "VASL.build.module.OBA$Module.getState()" because "mod" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/modules#2530]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | stewart.royce.king@gmail.com |
| Error Log | [7337 bytes](https://vassalengine.org/files/gh/0450d35bc98f0bdcbd104f9e891d8dff69152d8e) |

<pre>deleting OBA modules

VASL v6.6.2 3.5.8

java.lang.NullPointerException: Cannot invoke "VASL.build.module.OBA$Module.getState()" because "mod" is null
 at VASL.build.module.OBA$UpdateModule.executeCommand(OBA.java:262)
 at VASSAL.command.Command.execute(Command.java:62)
 at VASSAL.chat.CommandDecoder.lambda$propertyChange$0(CommandDecoder.java:40)
 at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
</pre>

**Comment by Cattlesquat** [comment]
VASL-specific code on _both_ stacks. @uckelman => move to VASL

**Comment by derimmer** [comment]
fixed by VASL PR#1044; will be issued in VASL6.6.4
