### ISSUE TITLE
[VASL] NullPointerException: Cannot invoke "VASL.LOS.Map.Hex.getBaseHeight()" because the return value of "VASL.LOS.Map.Map.getHex(String)" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/modules#2652]
| ABR | |
|-----|-----|
| Version | 3.6.15 |
| Reporter | pierre.oliver@start.ca |
| Error Log | [13759 bytes](https://vassalengine.org/files/gh/9c3526a25cc30d1bf2c39ff42b914ee7d0e7455f) |

<pre>Was trying to add overlays to ASL boards. Running latest versions of VASSAL and VASL

VASL v6.6.5-beta3 3.6.15

java.lang.NullPointerException: Cannot invoke "VASL.LOS.Map.Hex.getBaseHeight()" because the return value of "VASL.LOS.Map.Map.getHex(String)" is null
 at VASL.build.module.map.boardPicker.Overlay.transform(Overlay.java:519)
 at VASL.build.module.map.boardPicker.Overlay.<init>(Overlay.java:75)
 at VASL.build.module.map.boardPicker.ASLBoardSlot.overlap(ASLBoardSlot.java:194)
 at VASL.build.module.map.boardPicker.ASLBoardSlot.checkOverlap(ASLBoardSlot.java:151)
</pre>

**Comment by derimmer** [comment]
Transferred to VASL#1406

**Comment by derimmer** [comment]
Undo, closed by mistake.

**Comment by derimmer** [comment]
User confirms that problem fixed by 6.6.6
