### ISSUE TITLE
[Unnamed module] IllegalBuildException: failed to load class VASSAL.build.module.MyCounterFactory

### ISSUE THREAD

**Issue by uckelman** [vassalengine/modules#2773]
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter | alexmohr0404@gmx.de |
| Error Log | [4800 bytes](https://vassalengine.org/files/gh/89322b40cac3d1583aa0a691261b07127b1777e0) |

<pre>I followed the Programming instructions for creating custom modules. :( (https://vassalengine.org/wiki/Programming_Tutorial)

Unnamed module v0.0 3.7.5

VASSAL.build.IllegalBuildException: failed to load class VASSAL.build.module.MyCounterFactory
 at VASSAL.build.Builder.create(Builder.java:145)
 at VASSAL.build.Builder.build(Builder.java:80)
 at VASSAL.build.AbstractBuildable.build(AbstractBuildable.java:104)
 at VASSAL.build.GameModule.build(GameModule.java:785)
</pre>

**Comment by BrentEaston** [comment]
Have you copied the generated class files into your module? Even if you are running under the debugger in the IDE, using the IDE's version of the class files, you still need to copy the class files into the module for the first stage of the Class Loader to find the classes.

You don't have to update the class files in the module until you run the module outside of the IDE, you just need some version of them in the module to start with

**Comment by ironsmines** [comment]
I am trying to load a custom class into my module as well. I am getting an error trying to import a class as well. How do I load a class into my module?

java.lang.ClassNotFoundException: Unable to load class C:\Users\larry\Documents\WarRoom-Vassal\modules\CombatDiceRoller.class
	at VASSAL.tools.DataArchive.findClass(DataArchive.java:518)
	at VASSAL.tools.DataArchive.loadClass(DataArchive.java:491)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at VASSAL.configure.ConfigureTree.importConfigurable(ConfigureTree.java:1033)
	at VASSAL.configure.ConfigureTree$6.actionPerformed(ConfigureTree.java:642)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1022)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1066)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.io.FileNotFoundException: 'C:\Users\larry\Documents\WarRoom-Vassal\modules\CombatDiceRoller/class.class' not found in C:\Users\larry\Documents\WarRoom-Vassal\modules\warroom_2_0.vmod
	at VASSAL.tools.DataArchive.getInputStream(DataArchive.java:237)
	at VASSAL.tools.DataArchive.findClass(DataArchive.java:514)
	... 41 more

**Comment by BrentEaston** [comment]
Need more details. How did you load the custom class? What screen? What did you input? At what point does the error occur.

It looks like you are entering a filename in the import field. It is supposed to be a . separated full class name of a class that already exists in the module.

If you can, jump onto the Vassal Discord server and ask for help there. easier to run through it.

**Comment by ironsmines** [comment]
I was trying to load the custom class via the editor for my module. That is what generated the error.
What screen? - I don't know how to answer that one.
Input? - Nothing, I di not get that far.
How do I get my class into the module. That is what I was trying to do.

**Comment by ironsmines** [comment]
I am on Discord and joined to Vassal Discord as larryirons.
